### ISSUE TITLE
After user confirms that he sent the M-PESA payment, the overlay confirmation is wrong.

### ISSUE THREAD

**Issue by steffenkrogmann** [Kukuza/mobile-wallet#103]
it currently shows "transaction successful", but the transaction is only successful after the agent confirmed payment receipt.

Currently (wrong):
![image](https://user-images.githubusercontent.com/58551410/163143599-f5b6942e-ccb2-427a-87c3-7643ce835bca.png)

it should look like this:
![image](https://user-images.githubusercontent.com/58551410/163143909-373ba3c0-17d5-4043-8354-6edc84990f35.png)

Figma:
https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=4364%3A6621

**Comment by steffenkrogmann** [comment]
use existing overlay /modal and use text

"Thank you!

After your agents confirms of M-PESA payment receipt. Your cUSD will be deposited to your wallet. Do not close this page."

@Alphonce-Mutebi

**Comment by Alphonce-Mutebi** [comment]
@steffenkrogmann this should be fixed. Please retest
