### ISSUE TITLE
Reminder: We should find  a way to inform/remind users that they should ensure that they have enough balance in their fiat wallets to cater for additional fees

### ISSUE THREAD

**Issue by ClaireLagat** [Kukuza/mobile-wallet#125]
The user should be able to cover fees such as m-pesa transaction fees. Context info: the user had dark mode enabled.
If the requesting the user sends the fulfilling user (agent) anything less than the exact amount they should pay, it might result in unpleasant situations such as their cUSD being held in the blockchain until the user receives the full amount. -Will work on wording
![image](https://user-images.githubusercontent.com/102159494/164177126-9baf7872-cd91-484c-8fe4-a712c12b3008.png)

**Comment by steffenkrogmann** [comment]
@ClaireLagat we also need to tell them that they need to cover the M-PESA fee.

When a user needs to send 1,000 KSH, it means the agent needs to receive a net 1,000 KSH

When the agent only receives 990, we have a weird edge case
