### ISSUE TITLE
Daily Limit Prompt - Fulfill Withdraw Request

### ISSUE THREAD

**Issue by Chegemartinx** [Kukuza/mobile-wallet#133]
Agent who tries to fulfill a  withdraw request above cUSD 1000 or equivalent and has a daily max limit of cUSD 1,000 gets this prompt

![image](https://user-images.githubusercontent.com/63787845/164433009-5048de9f-80ce-4496-af70-6bd24e6380ec.png)

Figma link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=5945%3A10787

**Comment by steffenkrogmann** [comment]
covered in design changes
