### ISSUE TITLE
[ Bug ] [ UI ] Align transaction fees calculations and display with the smart contract. 

### ISSUE THREAD

**Issue by Allen-Muhani** [Kukuza/mobile-wallet#136]
Align the terms.
- [ ] agentFees
- [ ] wakalaFees
- [ ] grossfees
- [ ] amount

**Comment by steffenkrogmann** [comment]
@Allen-Muhani Are you driving this forward? or do you need anything from anyone?

We should probably also stick to the same wording for user/client and agent?

I use "User", but that is probably not good.

@Chegemartinx let's go with client for the Wakala feature?

**Comment by Chegemartinx** [comment]
Agreed @steffenkrogmann

**Comment by steffenkrogmann** [comment]
redundant now
