### ISSUE TITLE
Design Update / Raise Account Limit/ Settings page

### ISSUE THREAD

**Issue by Chegemartinx** [Kukuza/mobile-wallet#140]
In the settings page, when the user want to raise the account limit. They get a pop up asking them "Please contact wakala@support.com if you want to raise your daily send limit" instead of the existing coming soon pop up. 

![image](https://user-images.githubusercontent.com/63787845/164470242-893c889e-9572-4c57-8a3e-82b647a2a5e3.png)

Figma link: https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=1238%3A3014

**Comment by steffenkrogmann** [comment]
covered in design changes
