### ISSUE TITLE
Preferred mpesa phone number for payment/txn

### ISSUE THREAD

**Issue by Chegemartinx** [Kukuza/mobile-wallet#158]
We need to figure out a way we can have users add/confirm their preferred mpesa phone number for payment/txn. The reason being some users may register their wallets with other mobile service providers such as Airtel and Telcom which probably might not be ideal for mobile money.

**Comment by steffenkrogmann** [comment]
In a v1 we can probably do a disclaimer text thing.
wallet phone number needs to be m-pesa number.
