### ISSUE TITLE
[BUG] Unhandled promise rejection: Error: unknown account

### ISSUE THREAD

**Issue by Alphonce-Mutebi** [Kukuza/mobile-wallet#30]
I am using  contractkit 1.5.2 with react native. When the function  containing the code block below is called:
```
    let cUSDcontract = await kit.contracts.getStableToken();
    let contract = new kit.connection.web3.eth.Contract(
      wakalaEscrowAbi as AbiItem[],
      WAKALA_CONTRACT_ADDRESS
    );
    console.log("******************************");
    const user = {
      publicAdress: "0x9FDf3F87CbEE162DC4a9BC9673E5Bb6716186757",
    };

    const tx = await contract.methods.initializeDepositTransaction(2).send({
      from: user.publicAdress,
      feeCurrency: cUSDcontract.address,
    });

    let receipt = await tx.waitReceipt();
    console.log(receipt);

    console.log("******************************");
```
The following error is returned:
`
[Unhandled promise rejection: Error: unknown account]
at node_modules/@celo/connect/lib/utils/rpc-caller.js:137:16 in decoratedCallback
at http://192.168.100.179:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:481843:16 in onreadystatechange
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:601:4 in setReadyState
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:396:6 in __didCompleteResponse
at node_modules/react-native/Libraries/vendor/emitter/_EventEmitter.js:135:10 in EventEmitter#emit`

**Comment by lopeselio** [comment]
you can try `contract = new kit.web3.eth.Contract(ContractName.abi, address)`
