### ISSUE TITLE
Magic Reveal link with kukuza logo

### ISSUE THREAD

**Issue by steffenkrogmann** [Kukuza/mobile-wallet#33]
https://reveal.magic.link/wakala

needs to be changed to 

https://reveal.magic.link/kukuza

incl logo

**Comment by Chegemartinx** [comment]
Design updated: 
Find the figma link

https://www.figma.com/file/ERJ7bYyBWdqJw1ID9nZJ2N/Wakala?node-id=104%3A3



Also Kukuza Logo attached both PNG and SVG
![Group 778](https://user-images.githubusercontent.com/63787845/164250121-85889909-bca8-4349-8dc1-7e2d935c65fa.png)
![Group 778](https://user-images.githubusercontent.com/63787845/164250146-720c4680-c732-44d1-917e-f7f69b928a33.svg)

**Comment by Chegemartinx** [comment]
Design updated for magic link.

**Comment by steffenkrogmann** [comment]
Emailed Magic

**Comment by steffenkrogmann** [comment]
https://reveal.magic.link/kukuza

That link is working now @Alphonce-Mutebi
