### ISSUE TITLE
[ Bug ] Stream line authentication.

### ISSUE THREAD

**Issue by Allen-Muhani** [Kukuza/mobile-wallet#46]
- Invalid address on back navigation.
- Auth Screen [Error: Magic SDK Error: [MODAL_NOT_READY] Modal is not ready.] on screens that require <magic.Relayer>

Magic SDK Error: [MODAL_NOT_READY] Modal is not ready.
at http://192.168.245.229:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:205813:293 in _createSuperInternal
at node_modules/@magic-sdk/provider/dist/cjs/index.js:1:20915 in $#constructor
at http://192.168.245.229:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:206976:16 in In
at node_modules/@magic-sdk/react-native/dist/cjs/index.js:1:9886 in D$argument_2
at node_modules/@magic-sdk/react-native/dist/cjs/index.js:1:1121 in <global>
at node_modules/@magic-sdk/react-native/dist/cjs/index.js:1:1169 in u
at node_modules/@magic-sdk/provider/dist/cjs/index.js:1:1196 in o

[Unhandled promise rejection: Error: Magic SDK Error: [MODAL_NOT_READY] Modal is not ready.]
at http://192.168.245.229:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:205813:293 in _createSuperInternal
at node_modules/@magic-sdk/provider/dist/cjs/index.js:1:20915 in $#constructor
at http://192.168.245.229:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:206976:16 in In
at node_modules/@magic-sdk/react-native/dist/cjs/index.js:1:9886 in D$argument_2
at node_modules/@magic-sdk/react-native/dist/cjs/index.js:1:1121 in <global>
at node_modules/@magic-sdk/react-native/dist/cjs/index.js:1:1169 in u
at node_modules/@magic-sdk/provider/dist/cjs/index.js:1:1196 in o

**Comment by Alphonce-Mutebi** [comment]
@Allen-Muhani please retest
