### ISSUE TITLE
[ Bug ] Home page transactions list filter.

### ISSUE THREAD

**Issue by Allen-Muhani** [Kukuza/mobile-wallet#49]
Should only contain new transactions cc @Chegemartinx , @steffenkrogmann

**Comment by steffenkrogmann** [comment]
@Allen-Muhani what do you mean by new transactions?

Transactions that have not been fulfilled, yet, right?

**Comment by Allen-Muhani** [comment]
transactions that have not yet been paired to an agent. @steffenkrogmann
