### ISSUE TITLE
[ Discussion ] Go through the currency conversion flow chat and provide feedback. 

### ISSUE THREAD

**Issue by Allen-Muhani** [Kukuza/mobile-wallet#532]

**Comment by Allen-Muhani** [comment]
![Screenshot from 2022-06-14 17-08-46](https://user-images.githubusercontent.com/34819411/173598042-f78004d4-2995-43ed-8c03-f8a39be3fd6c.png)

**Comment by steffenkrogmann** [comment]
i put it on dework
