### ISSUE TITLE
Error when trying to accept a request

### ISSUE THREAD

**Issue by steffenkrogmann** [Kukuza/mobile-wallet#74]
I tried it with all requests in the feed. Always an error. 
The reason is not the balance, I have enough.

Only thing that comes to mind is that I could not (or should not be able to) accept my own requests.
But I did not post all of the requests that are in the feed. So I guess there is an error here.

I used the Expo build and cleared the cache and deleted all app data before I tested.

@Allen-Muhani @Alphonce-Mutebi 

![Screenshot_20220413-011707.png](https://user-images.githubusercontent.com/58551410/163069747-31330db7-a3fe-449c-88c2-bb114af0a8da.png)

**Comment by steffenkrogmann** [comment]
@Alphonce-Mutebi 

I just tried again with the 7cUSD request you just posted. accepting that one worked!

**Comment by Allen-Muhani** [comment]
@steffenkrogmann  Please verify
