### ISSUE TITLE
User cannot "Swipe to Confirm" that he sent the M-PESA payment.

### ISSUE THREAD

**Issue by steffenkrogmann** [Kukuza/mobile-wallet#75]
@Alphonce-Mutebi and I tested.

We were able to
- post a request
- accept a request
- accepting requesst payment prompt appeared on the users phone (Alphonce).
- user was not able to "swipe to confirm" the M-PESA payment.

**Comment by Allen-Muhani** [comment]
@steffenkrogmann  Please verify
