### ISSUE TITLE
Change top up request confirmation UI

### ISSUE THREAD

**Issue by steffenkrogmann** [Kukuza/mobile-wallet#84]
Top up amount
in KSH

Fee
cUSD 0.05 (can be hardcoded for now)

Total you receive
in cUSD

(Math: top up amount in ksh * conversion rate to cUSD - fee in cUSD = cUSD you receive)

Replace with a swipe to confirm button.
Related issue: https://github.com/Kukuza/mobile-wallet/issues/87

![image](https://user-images.githubusercontent.com/58551410/163129332-065a23e6-016f-4ad3-b373-2a785695051a.png)

**Comment by steffenkrogmann** [comment]
@Chegemartinx please adapt the designs as well, for everything basically :-D

**Comment by Chegemartinx** [comment]
Design updated accordingly

**Comment by Alphonce-Mutebi** [comment]
@steffenkrogmann  please review
