### ISSUE TITLE
Continue button on top up request confirmation page is not responding well

### ISSUE THREAD

**Issue by steffenkrogmann** [Kukuza/mobile-wallet#87]
The clickable area seems to be very small.

Also needs to be replaced with a swipe to confirm button.

Related issue: https://github.com/Kukuza/mobile-wallet/issues/84

![image](https://user-images.githubusercontent.com/58551410/163130540-b21539fb-e6b4-4f72-86fa-e71a6ac5e0d7.png)

**Comment by Chegemartinx** [comment]
Slide button updated on the design for this page

**Comment by steffenkrogmann** [comment]
replace with swipe to confirm @Mutinda-Kioko
