### ISSUE TITLE
When i refresh the feed, it sometimes hangs and i need to close the whole app and restart again

### ISSUE THREAD

**Issue by steffenkrogmann** [Kukuza/mobile-wallet#91]
To do with magic?

**Comment by Alphonce-Mutebi** [comment]
@steffenkrogmann please retest and close if possible

**Comment by steffenkrogmann** [comment]
@Alphonce-Mutebi 
I am closing this for now.

I thought that yesterday after my first log in the feed kept loading. But cannot replicate it for now.
If it happens again, i ll file a new bug.

Should this also solve the issue that the wallet balance sometimes does not load? are those related?
