### ISSUE TITLE
Remove Okay button and Change Sentence

### ISSUE THREAD

**Issue by vkamunya** [Kukuza/mobile-wallet#92]
![image](https://user-images.githubusercontent.com/62050248/163134887-2d9cfb81-454b-423d-93e5-baae4ed2b6bb.png)

Remove Okay button.
Change last sentence to 'Do not exit this page'.

**Comment by steffenkrogmann** [comment]
not fixed in the current build,, yet @Mutinda-Kioko

**Comment by steffenkrogmann** [comment]
@Mutinda-Kioko 

You changed the whole text. Why?
if something is unclear, please ask. We are losing too much time like this.

This is how it looks like (bug):
![image](https://user-images.githubusercontent.com/58551410/163248231-0a938137-d856-4271-8613-cc144ce956a3.png)

Change text to this:

"We share your deposit request with the agent community. We will notify you once an agent has answered the request. It can take up to 4 minutes. Do not exit this page."

Heading (stays the same): "Request Shared"

Okay button is and stays removed.
