### ISSUE TITLE
Change UI of "Accept top up request"

### ISSUE THREAD

**Issue by steffenkrogmann** [Kukuza/mobile-wallet#94]
1. Member wants to top up KSH.. Should be limited to 2 digits after the decimal.

2. You earn cUSD 0.05

3. Total you send (agent currently pays the fee, at least on the UI, which should not be).

Math of total you send:
(Top up amount in KSH * conversion rate) - fee in cUSD = total you send

![image](https://user-images.githubusercontent.com/58551410/163137058-fc591e8a-3ab7-4b60-9ca0-124b44f78810.png)

**Comment by Chegemartinx** [comment]
Design updated.

**Comment by Alphonce-Mutebi** [comment]
@steffenkrogmann please review
