### ISSUE TITLE
Change text on the text board and remove 'okay' button.

### ISSUE THREAD

**Issue by ClaireLagat** [Kukuza/mobile-wallet#95]
1. Change the text on the board to 'request accepted and the user has been notified' and 'please do not exit this page'. 
2. Remove 'OKAY' and 'click okay to exit this page.

![image](https://user-images.githubusercontent.com/102159494/163138383-aaca3dff-3bd9-404b-96ab-ff531ca12642.png)

**Comment by steffenkrogmann** [comment]
@Mutinda-Kioko Please change title to "Request Accepted"

@ClaireLagat You missed the headline in the text change, so @Mutinda-Kioko has to do it again ;)
Let's pay more attention
